# Generated by Django 5.2 on 2025-04-07 18:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(unique=True, verbose_name='Номер столика')),
                ('seats', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество мест')),
                ('location', models.CharField(choices=[('HL', 'Зал у окна'), ('TR', 'Терраса')], max_length=2, verbose_name='Расположение столика')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Фамилия Имя бронирующего')),
                ('reservation_time', models.DateTimeField(verbose_name='Дата и время бронирование столика')),
                ('duration_minutes', models.IntegerField(verbose_name='Продолжительность брони')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.table')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Бронь',
            },
        ),
    ]
